name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: |
            '11'
            '21'
          distribution: 'temurin'
          cache: maven
      - name: Install tiles
        run: cd support && mvn -f pom-tiles.xml install
      - name: Install support composites
        run: cd support && mvn install
      - name: All other things
        run: mvn install
