name: Java CI

on: [push]

jobs:
  build-java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install tiles
        run: cd support && mvn -f pom-tiles.xml install
      - name: Install support composites
        run: cd support && mvn install
      - name: All other things except examples
        run: mvn install
  build-java21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Install tiles
        run: cd support && mvn -f pom-tiles.xml install
      - name: Install support composites
        run: cd support && mvn install
      - name: All other things except examples
        run: mvn install
      - name: Examples
        working-directory: examples
        run: mvn package

